# -*- coding: utf-8 -*-
"""DataCo SMART SUPPLY CHAIN FOR BIG DATA ANALYSIS

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1pMGqPkUQHDeVJBISzxNJoHX1I9NvbFM_

# **Optimización de la Cadena de Suministro y Desempeño Comercial**

La base de datos se encuentra en el sig enlace https://www.kaggle.com/datasets/shashwatwork/dataco-smart-supply-chain-for-big-data-analysis/data
"""

# 1. Instalar la librería oficial ligera de Kaggle
!pip install kagglehub pandas --quiet

import kagglehub
import pandas as pd
import os

# 2. Descargar la última versión del dataset DataCo 3PL/Supply Chain
path = kagglehub.dataset_download("shashwatwork/dataco-smart-supply-chain-for-big-data-analysis")
print("✅ Ruta local del dataset descargado:", path)

# 3. Ubicar el archivo CSV dentro de la ruta descargada
archivo_csv = os.path.join(path, "DataCoSupplyChainDataset.csv")

# 4. Cargar en Pandas (usamos encoding='latin1' por los caracteres especiales del dataset)
df = pd.read_csv(archivo_csv, encoding='latin1')

print(f"\n📊 Base de datos cargada con éxito: {df.shape[0]:,} filas y {df.shape[1]} columnas.")
df.head()

# 1. Ver las primeras 5 filas para ver el aspecto
print(df.head())

# 2. Ver cuántas filas y columnas tenemos (aprox 180k filas, 53 columnas)
print(df.shape)

# 3. Ver un resumen de qué tipo de datos tiene cada columna y cuántos nulos hay
print(df.info())

# 1. Calcular el porcentaje de nulos por columna para tomar decisiones
nulos_por_columna = df.isnull().sum()
porcentaje_nulos = (df.isnull().sum() / len(df)) * 100
print(pd.DataFrame({'Nulos': nulos_por_columna, '%': porcentaje_nulos}).sort_values('%', ascending=False))

# 2. Rellenar los nulos estratégicamente:
# Para 'Customer State' (estado del cliente): lo relleno con 'Desconocido'
df['Customer State'] = df['Customer State'].fillna('Desconocido')

# Para 'Customer City' (ciudad): igual, relleno con 'Desconocido'
df['Customer City'] = df['Customer City'].fillna('Desconocido')

# Para 'Product Description': la relleno con 'Sin descripción' (no es crítica para números)
df['Product Description'] = df['Product Description'].fillna('Sin descripción')

# 3. ¿Y si hay filas donde falte 'Sales' (ventas) o 'Order Item Total' (costo)?
# Esas son críticas. Si faltan, no puedo calcular margen. Las elimino (son muy pocas).
df = df.dropna(subset=['Sales', 'Order Item Total'])

# 1. Renombrar las columnas problemáticas a nombres simples
df.rename(columns={
    'order date (DateOrders)': 'order_date',
    'shipping date (DateOrders)': 'shipping_date'
}, inplace=True)

# 2. Verificar que el cambio funcionó (debe mostrar 'order_date' y 'shipping_date')
print("Columnas de fecha después de renombrar:")
print(df[['order_date', 'shipping_date']].head())

# Convertir a datetime (formato fecha-hora)
df['order_date'] = pd.to_datetime(df['order_date'], errors='coerce')
df['shipping_date'] = pd.to_datetime(df['shipping_date'], errors='coerce')

# Verificar cuántas fechas no se pudieron convertir (debería ser 0 o casi 0)
fechas_nulas_order = df['order_date'].isnull().sum()
fechas_nulas_shipping = df['shipping_date'].isnull().sum()
print(f'Fechas de orden no convertidas: {fechas_nulas_order}')
print(f'Fechas de envío no convertidas: {fechas_nulas_shipping}')

# Eliminar filas donde la fecha sea nula (por si acaso)
df = df.dropna(subset=['order_date', 'shipping_date'])

# Calcular la diferencia en días
df['dias_de_entrega'] = (df['shipping_date'] - df['order_date']).dt.days

# Extraer mes, año y nombre del mes para los futuros reportes
df['mes'] = df['order_date'].dt.month
df['año'] = df['order_date'].dt.year
df['nombre_mes'] = df['order_date'].dt.month_name()

# Ver las primeras filas para confirmar que todo salió bien
print(df[['order_date', 'shipping_date', 'dias_de_entrega', 'nombre_mes']].head())

# Ver un resumen estadístico de los días de entrega (media, mín, máx)
print(df['dias_de_entrega'].describe())

# 1. Eliminar duplicados por si acaso (usando 'Order Id' que ya convertimos a 'order_id' con la limpieza inicial)
# Nota: asegúrate de que se llame 'order_id'. Si no, búscala en df.columns.
# Normalmente es 'Order Id' -> lo convertimos a 'order_id' al inicio.
if 'order_id' in df.columns:
    df = df.drop_duplicates(subset=['order_id'], keep='first')
else:
    # Si por algún motivo se llama 'Order Id', la renombramos
    df.rename(columns={'Order Id': 'order_id'}, inplace=True)
    df = df.drop_duplicates(subset=['order_id'], keep='first')

# 2. Guardar la base de datos completamente limpia y actualizada
df.to_csv('DataCoSupplyChain_Limpio_y_Actualizado.csv', index=False)

print("✅ ¡FASE 1 COMPLETADA CON ÉXITO!")
print(f"📊 Registros finales después de la limpieza: {len(df)}")
print("📁 Archivo guardado como 'DataCoSupplyChain_Limpio_y_Actualizado.csv'")

# Verificación rápida: mira las primeras 2 filas de las columnas de fecha
print(df[['order_date', 'shipping_date']].head(2))

# ------------------------------------------------------------
# RENOMBRAR COLUMNAS CLAVE (para que funcionen en los KPIs)
# ------------------------------------------------------------
df.rename(columns={
    'Order Id': 'order_id',
    'Delivery Status': 'delivery_status',
    'Department Name': 'department_name',
    'Sales': 'sales',
    'Order Item Total': 'order_item_total',
    'Customer Segment': 'customer_segment',
    'Customer City': 'customer_city',
    'Customer State': 'customer_state',
    'Shipping Mode': 'shipping_mode',
    'order date (DateOrders)': 'order_date',      # ya lo hiciste antes, pero por si acaso
    'shipping date (DateOrders)': 'shipping_date' # igual
}, inplace=True)

# Verificar que los nombres cambiaron correctamente
print("✅ Columnas renombradas. Las primeras filas:")
print(df[['order_id', 'delivery_status', 'department_name', 'sales', 'order_item_total']].head())

# ------------------------------------------------------------
# KPI 1: % de Entregas a Tiempo (El rey de los KPIs logísticos)
# ------------------------------------------------------------
total_pedidos = df['order_id'].nunique()  # Número total de pedidos únicos

# Contamos cuántos pedidos tienen el estado "Shipping on time"
entregas_a_tiempo = df[df['delivery_status'] == 'Shipping on time']['order_id'].nunique()

# Calculamos el porcentaje
porcentaje_on_time = (entregas_a_tiempo / total_pedidos) * 100

print(f"📦 Total de pedidos únicos: {total_pedidos}")
print(f"✅ Pedidos entregados a tiempo: {entregas_a_tiempo}")
print(f"⏰ Porcentaje de entregas a tiempo: {porcentaje_on_time:.2f}%")
print(f"⚠️  Porcentaje de entregas tardías: {100 - porcentaje_on_time:.2f}% (¡ALERTA COMERCIAL!)\n")


# ------------------------------------------------------------
# KPI 2: Ticket Promedio por Pedido (¿Cuánto gasta un cliente de media?)
# ------------------------------------------------------------
# Sumamos todas las ventas y las dividimos entre el número de pedidos únicos
ventas_totales = df['sales'].sum()
ticket_promedio = ventas_totales / total_pedidos

print(f"💰 Ventas totales del histórico: ${ventas_totales:,.2f}")
print(f"🛒 Ticket promedio por pedido: ${ticket_promedio:,.2f}\n")

# Añadir la columna 'Order Profit Per Order' al rename (si no la habías puesto)
df.rename(columns={
    'Order Profit Per Order': 'order_profit_per_order'
}, inplace=True)

# Verifica que ahora existen las columnas 'sales' y 'order_profit_per_order'
print("✅ Columnas disponibles para el KPI 3:")
print(df[['sales', 'order_profit_per_order']].head())

# ------------------------------------------------------------
# KPI 3 CORREGIDO Y FUNCIONAL: Margen de Rentabilidad REAL
# ------------------------------------------------------------

# Calculamos el margen real: Beneficio / Ventas
df['margen_real'] = df['order_profit_per_order'] / df['sales']

# Agrupamos por Departamento (ojo: ¿cómo se llama ahora?
# Si lo renombraste como 'department_name', úsalo. Si no, usa 'Department Name')
# Voy a usar el nombre original por si acaso, pero tú tienes 'department_name' creado.
# Usaré 'department_name' porque lo renombraste en el paso anterior.
margen_real_por_departamento = df.groupby('department_name')['margen_real'].mean().sort_values(ascending=False)

print("🏆 Top 5 Departamentos con MEJOR margen REAL:")
print(margen_real_por_departamento.head(5).to_string(float_format="{:.2%}".format))
print("\n")
print("📉 Top 5 Departamentos con PEOR margen REAL (los que hay que revisar):")
print(margen_real_por_departamento.tail(5).to_string(float_format="{:.2%}".format))

# Margen general de la empresa
margen_general = df['order_profit_per_order'].sum() / df['sales'].sum()
print(f"\n📊 Margen de beneficio NETO de toda la empresa: {margen_general:.2%}")

# ------------------------------------------------------------
# ANÁLISIS 1: Desempeño por Segmento de Cliente
# ------------------------------------------------------------
print("="*50)
print("📊 ANÁLISIS POR SEGMENTO DE CLIENTE")
print("="*50)

# Agrupamos por segmento
segmento_ventas = df.groupby('customer_segment').agg(
    Total_Ventas=('sales', 'sum'),
    Total_Pedidos=('order_id', 'nunique'),
    Ticket_Promedio=('sales', 'mean'),
    Margen_Promedio=('margen_real', 'mean')
).sort_values('Total_Ventas', ascending=False)

# Dar formato a los números
segmento_ventas['Total_Ventas'] = segmento_ventas['Total_Ventas'].map('${:,.2f}'.format)
segmento_ventas['Ticket_Promedio'] = segmento_ventas['Ticket_Promedio'].map('${:,.2f}'.format)
segmento_ventas['Margen_Promedio'] = segmento_ventas['Margen_Promedio'].map('{:.2%}'.format)

print(segmento_ventas)
print("\n📌 Insight: ¿Qué segmento tiene el ticket más alto? ¿Cuál vende más en volumen?\n")


# ------------------------------------------------------------
# ANÁLISIS 2: Top 5 Estados con mayor facturación (Geografía)
# ------------------------------------------------------------
print("="*50)
print("🗺️ TOP 5 ESTADOS CON MAYOR FACTURACIÓN")
print("="*50)

estados_top = df.groupby('customer_state').agg(
    Total_Ventas=('sales', 'sum'),
    Total_Pedidos=('order_id', 'nunique'),
    Margen=('margen_real', 'mean')
).sort_values('Total_Ventas', ascending=False).head(5)

estados_top['Total_Ventas'] = estados_top['Total_Ventas'].map('${:,.2f}'.format)
estados_top['Margen'] = estados_top['Margen'].map('{:.2%}'.format)
print(estados_top)

# Identificar el estado con mayor ticket (para ver dónde está el cliente premium)
ticket_por_estado = df.groupby('customer_state')['sales'].mean().sort_values(ascending=False)
print(f"\n🏆 Estado con el ticket promedio MÁS ALTO: {ticket_por_estado.index[0]} (${ticket_por_estado.iloc[0]:.2f})")
print(f"📉 Estado con el ticket promedio MÁS BAJO: {ticket_por_estado.index[-1]} (${ticket_por_estado.iloc[-1]:.2f})\n")


# ------------------------------------------------------------
# ANÁLISIS 3: Métodos de Pago Preferidos (comportamiento del consumidor)
# ------------------------------------------------------------
print("="*50)
print("💳 MÉTODOS DE PAGO UTILIZADOS")
print("="*50)

# La columna se llama 'Type' (Débito, Transferencia, Pago, Efectivo)
# Si está en mayúscula, asegúrate de renombrarla o usar el nombre exacto.
# Como no la renombramos antes, usamos 'Type' directamente.
metodos_pago = df['Type'].value_counts()
metodos_pago_porcentaje = df['Type'].value_counts(normalize=True) * 100

pagos_df = pd.DataFrame({
    'Cantidad': metodos_pago,
    'Porcentaje': metodos_pago_porcentaje
})
print(pagos_df)

print("\n📌 Recomendación: Si 'TRANSFER' es el método más usado, asegurar que los datos bancarios estén siempre visibles en el checkout.")

!pip install matplotlib seaborn

import matplotlib.pyplot as plt
import seaborn as sns
import pandas as pd
import numpy as np

# Configurar estilo profesional
sns.set_style("whitegrid")
sns.set_palette("viridis")

# Crear figura con 4 subplots (2 filas x 2 columnas)
fig, axes = plt.subplots(2, 2, figsize=(16, 12))
fig.suptitle('Dashboard Comercial - DataCo Supply Chain', fontsize=20, fontweight='bold')

# ------------------------------------------------------------
# GRÁFICO 1: Ventas por Segmento (Barras)
# ------------------------------------------------------------
seg_data = df.groupby('customer_segment')['sales'].sum().sort_values(ascending=False)
if not seg_data.empty:
    seg_data.plot(kind='bar', ax=axes[0,0], color=['#1f77b4', '#ff7f0e', '#2ca02c'])
    axes[0,0].set_title('Ventas Totales por Segmento de Cliente', fontsize=14)
    axes[0,0].set_ylabel('Ventas (USD)')
    axes[0,0].set_xlabel('Segmento')
    for i, v in enumerate(seg_data):
        axes[0,0].text(i, v + 50000, f'${v/1e6:.1f}M', ha='center', fontsize=11)

# ------------------------------------------------------------
# GRÁFICO 2: Top 5 Estados por Ventas (Barras horizontales)
# ------------------------------------------------------------
estados_top = df.groupby('customer_state')['sales'].sum().sort_values(ascending=False).head(5)
if not estados_top.empty:
    estados_top.plot(kind='barh', ax=axes[0,1], color='teal')
    axes[0,1].set_title('Top 5 Estados con Mayor Facturación', fontsize=14)
    axes[0,1].set_xlabel('Ventas (USD)')
    axes[0,1].set_ylabel('Estado')
    for i, v in enumerate(estados_top):
        axes[0,1].text(v + 50000, i, f'${v/1e6:.1f}M', va='center', fontsize=11)

# ------------------------------------------------------------
# GRÁFICO 3: Distribución de Métodos de Pago (Pastel)
# ------------------------------------------------------------
pagos = df['Type'].value_counts()
if not pagos.empty:
    axes[1,0].pie(pagos, labels=pagos.index, autopct='%1.1f%%', startangle=90, explode=[0.02]*len(pagos))
    axes[1,0].set_title('Métodos de Pago Utilizados', fontsize=14)
    axes[1,0].axis('equal')

# ------------------------------------------------------------
# GRÁFICO 4: Ticket Promedio vs Margen por Departamento (Burbujas)
# ------------------------------------------------------------
# Eliminar posibles valores infinitos o nulos para evitar el gráfico en blanco
df_clean = df.dropna(subset=['margen_real', 'sales'])

dep_agg = df_clean.groupby('department_name').agg(
    ticket_promedio=('sales', 'mean'),
    margen_promedio=('margen_real', 'mean'),
    ventas_totales=('sales', 'sum')
).reset_index()

# Filtrar departamentos sin ventas o con margen 0 para no romper el gráfico
dep_agg = dep_agg[(dep_agg['ventas_totales'] > 0) & (dep_agg['margen_promedio'] > 0)]

if not dep_agg.empty:
    sizes = dep_agg['ventas_totales'] / dep_agg['ventas_totales'].max() * 1000
    scatter = axes[1,1].scatter(
        dep_agg['ticket_promedio'],
        dep_agg['margen_promedio'] * 100,
        s=sizes,
        alpha=0.6,
        c=dep_agg['margen_promedio'],
        cmap='RdYlGn',
        edgecolors='black'
    )
    axes[1,1].set_title('Ticket Promedio vs Margen por Departamento', fontsize=14)
    axes[1,1].set_xlabel('Ticket Promedio (USD)')
    axes[1,1].set_ylabel('Margen (%)')

    # Etiquetas solo para los departamentos con ventas significativas
    for idx, row in dep_agg.iterrows():
        if row['ventas_totales'] > 1e6:
            axes[1,1].annotate(row['department_name'],
                              (row['ticket_promedio'], row['margen_promedio']*100),
                              fontsize=8, ha='center', va='bottom')
    plt.colorbar(scatter, ax=axes[1,1], label='Margen (%)', shrink=0.6)
else:
    axes[1,1].text(0.5, 0.5, 'Datos insuficientes para gráfico de burbujas',
                   ha='center', va='center', transform=axes[1,1].transAxes)

plt.tight_layout(rect=[0, 0, 1, 0.96])

# ------------------------------------------------------------
# GUARDAR EL DASHBOARD EN UN ARCHIVO (La parte más importante)
# ------------------------------------------------------------
plt.savefig('dashboard_comercial.png', dpi=300, bbox_inches='tight')
print("✅ Dashboard guardado EXITOSAMENTE como 'dashboard_comercial.png'")

# Intentar mostrarlo en pantalla (puede que siga viéndose en blanco en Colab, pero el archivo sí existe)
plt.show()

from google.colab import files
files.download('dashboard_comercial.png')

print("🔍 Nombres de columnas clave:")
print("Late_delivery_risk" in df.columns)   # Debe dar True
print("Shipping Mode" in df.columns)        # Debe dar True
print("Category Name" in df.columns)        # Debe dar True

print("🔍 Nombres en minúscula que deberían existir:")
print("shipping_mode" in df.columns)        # Debe dar True (lo renombraste)
print("category_name" in df.columns)        # Depende: si ejecutaste el rename, True
print("late_delivery_risk" in df.columns)   # Debe dar True (existe original)

# ------------------------------------------------------------
# ANÁLISIS DE RIESGO DE RETRASO (Con nombres EXACTOS del DataFrame)
# ------------------------------------------------------------

print("="*50)
print("🔴 ANÁLISIS DE RIESGO POR MODO DE ENVÍO")
print("="*50)

# shipping_mode (ya está en minúscula) y Late_delivery_risk (con L mayúscula)
riesgo_por_envio = df.groupby('shipping_mode')['Late_delivery_risk'].mean().sort_values(ascending=False)
print(riesgo_por_envio.map('{:.1%}'.format))

print("\n" + "="*50)
print("🔴 TOP 10 CATEGORÍAS CON MAYOR RIESGO DE RETRASO")
print("="*50)

# Usamos 'Category Name' (con espacio) tal cual está en el DataFrame
riesgo_por_categoria = df.groupby('Category Name')['Late_delivery_risk'].mean().sort_values(ascending=False).head(10)
print(riesgo_por_categoria.map('{:.1%}'.format))

print("\n" + "="*50)
print("📦 DISTRIBUCIÓN DE MODOS DE ENVÍO (Top 5)")
print("="*50)
print(df['shipping_mode'].value_counts().head(5))

"""VALIDACION CRUZADA"""

# ------------------------------------------------------------
# 1. MAPEO MAESTRO: Aquí se definen TODOS los nombres estándar
#    (Agrega más columnas a medida que las necesites)
# ------------------------------------------------------------
mapeo_columnas = {
    'Order Id': 'order_id',
    'Sales': 'sales',  # <--- Lo convertimos a minúscula
    'Customer Segment': 'customer_segment',  # <--- Lo convertimos a minúscula
    'Category Name': 'category_name',  # <--- Lo convertimos a minúscula
    'Shipping Mode': 'shipping_mode',  # <--- Ya lo hiciste
    'Order Region': 'order_region',  # <--- Lo añadimos
    'Order State': 'order_state',  # <--- Lo añadimos
    'Order Item Quantity': 'order_item_quantity',  # <--- Lo añadimos
    'Late_delivery_risk': 'late_delivery_risk'  # <--- Lo pasamos a minúscula aunque ya lo estaba
}

# 2. APLICAR EL MAPEO DE UNA VEZ (Sobrescribimos las columnas)
df.rename(columns=mapeo_columnas, inplace=True)

# 3. VERIFICACIÓN INTELIGENTE (Mostramos cómo quedaron las que nos interesan)
print("✅ Nombres estandarizados aplicados. Verificando columnas clave:")
columnas_interes = ['order_id', 'sales', 'customer_segment', 'shipping_mode', 'category_name', 'order_region', 'order_state', 'order_item_quantity', 'late_delivery_risk']
for col in columnas_interes:
    estado = "✅" if col in df.columns else "❌ FALTA"
    print(f"  {estado} {col}")

import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split, cross_val_score, StratifiedKFold
from sklearn.preprocessing import StandardScaler, OneHotEncoder
from sklearn.compose import ColumnTransformer
from sklearn.pipeline import Pipeline
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import classification_report, confusion_matrix, roc_auc_score, RocCurveDisplay, ConfusionMatrixDisplay
import matplotlib.pyplot as plt
import seaborn as sns

# ------------------------------------------------------------
# 1. DEFINIR LAS VARIABLES (Todas en minúscula y con guión bajo)
# ------------------------------------------------------------
columnas_features = [
    'shipping_mode',         # Categórica
    'category_name',         # Categórica
    'customer_segment',      # Categórica
    'order_region',          # Categórica
    'order_state',           # Categórica
    'order_item_quantity',   # Numérica
    'sales'                  # Numérica
]

# Verificar que todas existen (esto ya no dará error, pero lo dejamos por seguridad)
missing = [col for col in columnas_features if col not in df.columns]
if missing:
    print(f"❌ Aún faltan: {missing}. Revisa el mapeo.")
else:
    print("✅ Todas las columnas seleccionadas existen.")

# 2. DEFINIR X e y
X = df[columnas_features]
y = df['late_delivery_risk']  # Ya está en minúscula por el mapeo

# 3. Eliminar nulos por si acaso
X = X.dropna()
y = y.loc[X.index]

print(f"📊 Tamaño del dataset: {X.shape[0]} registros, {X.shape[1]} features.")

# ------------------------------------------------------------
# 4. PREPROCESAMIENTO Y MODELO
# ------------------------------------------------------------
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42, stratify=y)

numeric_cols = ['order_item_quantity', 'sales']
categorical_cols = ['shipping_mode', 'category_name', 'customer_segment', 'order_region', 'order_state']

preprocessor = ColumnTransformer(
    transformers=[
        ('num', StandardScaler(), numeric_cols),
        ('cat', OneHotEncoder(handle_unknown='ignore', sparse_output=False), categorical_cols)
    ])

model = Pipeline(steps=[
    ('preprocessor', preprocessor),
    ('classifier', LogisticRegression(max_iter=1000, random_state=42, class_weight='balanced'))
])

# 5. VALIDACIÓN CRUZADA
cv = StratifiedKFold(n_splits=5, shuffle=True, random_state=42)
cv_scores = cross_val_score(model, X_train, y_train, cv=cv, scoring='accuracy')

print("\n" + "="*50)
print("🔬 VALIDACIÓN CRUZADA (5-Fold)")
print("="*50)
print(f"✅ Precisiones por fold: {np.round(cv_scores, 4)}")
print(f"📈 Precisión Media: {np.mean(cv_scores):.4f} (+/- {np.std(cv_scores):.4f})")

# 6. ENTRENAR Y EVALUAR
model.fit(X_train, y_train)
y_pred = model.predict(X_test)
y_proba = model.predict_proba(X_test)[:, 1]

print("\n" + "="*50)
print("📊 RENDIMIENTO EN PRUEBA")
print("="*50)
print(classification_report(y_test, y_pred, target_names=['A Tiempo', 'Tardío']))
print(f"🎯 AUC-ROC: {roc_auc_score(y_test, y_proba):.4f}")

# Extraer nombres de las features codificadas
preprocessor.fit(X_train)
feature_names = (numeric_cols +
                 list(preprocessor.named_transformers_['cat'].get_feature_names_out(categorical_cols)))

coeficientes = model.named_steps['classifier'].coef_[0]
importancia_df = pd.DataFrame({
    'Feature': feature_names,
    'Coeficiente': coeficientes
}).sort_values('Coeficiente', ascending=False)

print("="*50)
print("⚖️ TOP FACTORES QUE INCREMENTAN EL RIESGO (Positivos)")
print("="*50)
print(importancia_df.head(10).to_string(index=False))

COL_VENTAS = 'sales'
COL_SEGMENTO = 'customer_segment'
# Luego usas df[COL_VENTAS] en todo tu código

# Extraer los nombres de las features después del One-Hot Encoding
preprocessor.fit(X_train)
feature_names = (['order_item_quantity', 'sales'] +
                 list(preprocessor.named_transformers_['cat'].get_feature_names_out(
                     ['shipping_mode', 'category_name', 'customer_segment', 'order_region', 'order_state']
                 )))

# Coeficientes del modelo
coeficientes = model.named_steps['classifier'].coef_[0]

importancia_df = pd.DataFrame({
    'Feature': feature_names,
    'Coeficiente': coeficientes
}).sort_values('Coeficiente', ascending=False)

print("="*50)
print("⚡ TOP 10 FACTORES QUE MÁS AUMENTAN EL RIESGO DE RETRASO")
print("="*50)
print(importancia_df.head(10).to_string(index=False))

print("\n" + "="*50)
print("🛡️ TOP 10 FACTORES QUE MÁS REDUCEN EL RIESGO")
print("="*50)
print(importancia_df.tail(10).to_string(index=False))

# Guardar el DataFrame que ya tienes limpio y con todas las columnas
df.to_csv('dataco_supply_chain_limpio.csv', index=False, encoding='utf-8-sig')
print("✅ Archivo CSV guardado como 'dataco_supply_chain_limpio.csv'")

# Diccionario de estados de EE.UU. y territorios
estados_usa = {
    'PR': 'Puerto Rico',
    'CA': 'California',
    'NY': 'New York',
    'TX': 'Texas',
    'IL': 'Illinois',
    # ... añade los que necesites
}

# Crear una nueva columna con el nombre completo
df['customer_state_full'] = df['customer_state'].map(estados_usa)

# Verificar para PR
print(df[df['customer_state'] == 'PR'][['customer_state', 'customer_state_full']].head())

# ------------------------------------------------------------
# VERIFICACIÓN DE "PR" EN EL DATASET
# ------------------------------------------------------------

# 1. Filtrar todos los registros donde customer_state == 'PR'
pr_df = df[df['customer_state'] == 'PR']

# 2. Ver cuántos registros hay
print(f"📦 Registros con 'PR': {len(pr_df)}")
print(f"📊 Porcentaje del total: {len(pr_df)/len(df)*100:.2f}%")

# 3. Ver las ciudades (customer_city) asociadas a esos registros
print("\n🏙️ Ciudades que aparecen con 'PR':")
print(pr_df['customer_city'].unique())

# 4. Ver si existe columna 'customer_country' o 'order_region' para confirmar
if 'customer_country' in df.columns:
    print("\n🌎 Países asociados a 'PR':")
    print(pr_df['customer_country'].unique())
elif 'order_region' in df.columns:
    print("\n🌎 Regiones asociadas a 'PR':")
    print(pr_df['order_region'].unique())
else:
    print("\n⚠️ No hay columna de país/región para cruzar información.")

# 5. También puedes ver los estados completos (si existen)
if 'customer_state_full' in df.columns:
    print("\n📌 Nombres completos de estado:")
    print(pr_df['customer_state_full'].unique())

# 6. Opcional: ver una muestra de los datos con todas las columnas geográficas
print("\n🔍 Muestra de datos geográficos para 'PR':")
columnas_geo = [col for col in df.columns if any(key in col.lower() for key in ['city', 'state', 'country', 'region', 'zip'])]
print(pr_df[columnas_geo].head(10))

# Cargar el archivo
df = pd.read_csv('dataco_supply_chain_limpio.csv')

# ------------------------------------------------------------
# MAPEO MAESTRO (Todas las columnas que necesitas)
# ------------------------------------------------------------
mapeo_columnas = {
    'Order Id': 'order_id',
    'Sales': 'sales',
    'Customer Segment': 'customer_segment',
    'Category Name': 'category_name',
    'Shipping Mode': 'shipping_mode',
    'Order Region': 'order_region',
    'Order State': 'order_state',
    'Order Item Quantity': 'order_item_quantity',
    'Late_delivery_risk': 'late_delivery_risk',  # Ojo: mayúscula L
    'delivery_status': 'delivery_status',        # Ya está en minúscula, pero lo dejamos
    'Department Name': 'department_name',
    'Order Profit Per Order': 'order_profit_per_order'
}

df.rename(columns=mapeo_columnas, inplace=True)

print("✅ Columnas renombradas correctamente.")

import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import numpy as np

# ------------------------------------------------------------
# 1. CARGAR DATOS Y RENOMBRAR COLUMNAS
# ------------------------------------------------------------
df = pd.read_csv('dataco_supply_chain_limpio.csv')

mapeo = {
    'Order Id': 'order_id',
    'Sales': 'sales',
    'Customer Segment': 'customer_segment',
    'Category Name': 'category_name',
    'Shipping Mode': 'shipping_mode',
    'Order Region': 'order_region',
    'Order State': 'order_state',
    'Order Item Quantity': 'order_item_quantity',
    'Late_delivery_risk': 'late_delivery_risk',
    'delivery_status': 'delivery_status',
    'Department Name': 'department_name',
    'Order Profit Per Order': 'order_profit_per_order'
}
df.rename(columns=mapeo, inplace=True)

print(f"✅ DataFrame cargado: {df.shape[0]} filas y {df.shape[1]} columnas")
print("📊 Columnas clave disponibles:", [col for col in ['sales', 'order_id', 'late_delivery_risk', 'customer_segment'] if col in df.columns])

# ------------------------------------------------------------
# 2. CÁLCULO DE KPIs
# ------------------------------------------------------------
total_ventas = df['sales'].sum()
total_pedidos = df['order_id'].nunique()
ticket_promedio = total_ventas / total_pedidos

pedidos_on_time = df[df['late_delivery_risk'] == 0]['order_id'].nunique()
pct_on_time = (pedidos_on_time / total_pedidos) * 100

margen_neto = (df['order_profit_per_order'].sum() / total_ventas) * 100

ventas_segmento = df.groupby('customer_segment')['sales'].sum().sort_values(ascending=False)
ticket_segmento = df.groupby('customer_segment')['sales'].mean().sort_values(ascending=False)

# ------------------------------------------------------------
# 3. DASHBOARD (Mismo código que antes)
# ------------------------------------------------------------
sns.set_style("whitegrid")
sns.set_palette("viridis")
plt.rcParams['font.size'] = 12

fig = plt.figure(figsize=(16, 10))
grid = plt.GridSpec(2, 3, figure=fig, hspace=0.3, wspace=0.3)

# Tarjeta de KPIs
ax1 = fig.add_subplot(grid[0, 0])
ax1.axis('off')
ax1.set_title('📊 Resumen Ejecutivo', fontsize=16, fontweight='bold', loc='left')
texto_kpi = (
    f"💰 Ventas Totales\n${total_ventas:,.2f}\n\n"
    f"📦 Total Pedidos\n{total_pedidos:,}\n\n"
    f"🛒 Ticket Promedio\n${ticket_promedio:.2f}\n\n"
    f"📈 Margen Neto\n{margen_neto:.2f}%"
)
ax1.text(0.1, 0.5, texto_kpi, transform=ax1.transAxes, fontsize=14, verticalalignment='center',
         bbox=dict(boxstyle='round,pad=0.5', facecolor='#f0f4f8', edgecolor='#2c3e50', linewidth=2))

# Donut de entregas
ax2 = fig.add_subplot(grid[0, 1])
colores = ['#2ecc71', '#e74c3c']
valores = [pct_on_time, 100 - pct_on_time]
ax2.pie(valores, labels=['A Tiempo', 'Tardío'], autopct='%1.1f%%',
        colors=colores, startangle=90, pctdistance=0.85,
        wedgeprops=dict(width=0.4, edgecolor='white'))
ax2.text(0, 0, f'{pct_on_time:.1f}%', ha='center', va='center', fontsize=24, fontweight='bold')
ax2.text(0, -0.2, 'Entregas\nA Tiempo', ha='center', va='center', fontsize=12)
ax2.set_title('⏰ Desempeño Logístico', fontsize=14, fontweight='bold')

# Top 5 margen por departamento
ax3 = fig.add_subplot(grid[0, 2])
margen_dept = df.groupby('department_name').apply(
    lambda x: (x['order_profit_per_order'].sum() / x['sales'].sum()) * 100
).sort_values(ascending=False).head(5)
colores_barra = plt.cm.RdYlGn(np.linspace(0.3, 0.9, len(margen_dept)))[::-1]
ax3.barh(margen_dept.index, margen_dept.values, color=colores_barra)
ax3.set_xlabel('Margen (%)')
ax3.set_title('🏆 Top 5 Deptos. por Margen', fontsize=14, fontweight='bold')
for i, v in enumerate(margen_dept.values):
    ax3.text(v + 0.5, i, f'{v:.1f}%', va='center', fontsize=11)
ax3.set_xlim(0, margen_dept.max() * 1.2)

# Ventas por segmento
ax4 = fig.add_subplot(grid[1, 0:2])
colores_seg = ['#3498db', '#e67e22', '#2ecc71']
ventas_segmento.plot(kind='bar', ax=ax4, color=colores_seg, width=0.6)
ax4.set_title('💰 Ventas Totales por Segmento de Cliente', fontsize=14, fontweight='bold')
ax4.set_xlabel('Segmento')
ax4.set_ylabel('Ventas (USD)')
ax4.ticklabel_format(style='plain', axis='y')
for i, v in enumerate(ventas_segmento):
    ax4.text(i, v + 50000, f'${v/1e6:.1f}M', ha='center', va='bottom', fontsize=11)

# Ticket promedio por segmento
ax5 = fig.add_subplot(grid[1, 2])
ticket_segmento.plot(kind='bar', ax=ax5, color=['#9b59b6', '#f1c40f', '#e74c3c'], width=0.6)
ax5.set_title('🎫 Ticket Promedio por Segmento', fontsize=14, fontweight='bold')
ax5.set_xlabel('Segmento')
ax5.set_ylabel('Ticket Promedio (USD)')
for i, v in enumerate(ticket_segmento):
    ax5.text(i, v + 3, f'${v:.0f}', ha='center', va='bottom', fontsize=10)

# Guardar y mostrar
fig.suptitle('📋 Dashboard de KPIs Comerciales - DataCo Supply Chain', fontsize=22, fontweight='bold', y=0.98)
plt.tight_layout(rect=[0, 0, 1, 0.96])
plt.savefig('dashboard_kpi_python.png', dpi=300, bbox_inches='tight')
print("✅ Dashboard guardado como 'dashboard_kpi_python.png'")
plt.show()

import plotly.express as px
import pandas as pd

# Agrupar ventas por estado
estado_ventas = df.groupby('customer_state', as_index=False)['sales'].sum()

# Mapa de USA (necesitas el código de estado, ej: CA, TX, PR)
fig = px.choropleth(
    estado_ventas,
    locations='customer_state',        # Columna con códigos de estado
    locationmode='USA-states',         # Modo para USA
    color='sales',                     # Variable a colorear
    scope='usa',                       # Enfocar en USA
    color_continuous_scale='Viridis',  # Escala de colores profesional
    labels={'sales': 'Ventas Totales (USD)'},
    title='🗺️ Ventas Totales por Estado (DataCo)'
)

# Mejorar el layout
fig.update_layout(
    geo=dict(bgcolor='rgba(0,0,0,0)', lakecolor='lightblue'),
    title_font_size=20,
    height=600
)

fig.show()
# Guardar como HTML interactivo (ideal para GitHub)
fig.write_html('mapa_ventas_estados.html')
print("✅ Mapa guardado como 'mapa_ventas_estados.html'")

import plotly.express as px

# Agrupar por Departamento y Categoría
jerarquia_ventas = df.groupby(['department_name', 'category_name'], as_index=False)['sales'].sum()

fig = px.treemap(
    jerarquia_ventas,
    path=['department_name', 'category_name'],  # Jerarquía (Padre > Hijo)
    values='sales',
    color='sales',
    color_continuous_scale='Blues',
    title='📦 Distribución de Ventas por Departamento y Categoría',
    hover_data={'sales': ':$,.0f'}  # Formato de moneda al pasar el mouse
)

fig.update_layout(height=600, title_font_size=20)
fig.show()
fig.write_html('treemap_categorias.html')
print("✅ Treemap guardado como 'treemap_categorias.html'")

import matplotlib.pyplot as plt
import seaborn as sns

plt.figure(figsize=(10, 6))

# Gráfico de densidad (KDE) de las ventas
sns.kdeplot(data=df, x='sales', fill=True, color='#3498db', alpha=0.6, linewidth=2)

# Podemos segmentar por Segmento de Cliente para comparar
sns.kdeplot(data=df[df['customer_segment'] == 'Consumer'], x='sales', label='Consumer', fill=False, linestyle='--')
sns.kdeplot(data=df[df['customer_segment'] == 'Corporate'], x='sales', label='Corporate', fill=False, linestyle='-.')
sns.kdeplot(data=df[df['customer_segment'] == 'Home Office'], x='sales', label='Home Office', fill=False, linestyle=':')

plt.title('📈 Distribución del Ticket Promedio por Segmento (Densidad)', fontsize=16)
plt.xlabel('Ventas por Pedido (USD)')
plt.ylabel('Densidad')
plt.xlim(0, 800)  # Enfocar en el rango donde está el 95% de los datos para mejor visualización
plt.legend()
plt.grid(True, linestyle='--', alpha=0.5)
plt.tight_layout()
plt.savefig('densidad_tickets.png', dpi=300)
plt.show()

import matplotlib.pyplot as plt
import seaborn as sns

plt.figure(figsize=(14, 8))

# Filtramos para que se vean solo los departamentos con suficientes datos
top_deptos = df['department_name'].value_counts().head(8).index
df_filtered = df[df['department_name'].isin(top_deptos)]

# Violin Plot (combina boxplot con densidad)
sns.violinplot(data=df_filtered, x='department_name', y='margen_real', inner='quartile', palette='coolwarm', cut=0)

plt.title('🎻 Distribución del Margen por Departamento (Violin Plot)', fontsize=16)
plt.xlabel('Departamento')
plt.ylabel('Margen Real (%)')
plt.xticks(rotation=45, ha='right')  # Rotar etiquetas si son largas
plt.axhline(y=df_filtered['margen_real'].mean(), color='red', linestyle='--', label=f'Margen Promedio Global ({df_filtered["margen_real"].mean():.2%})')
plt.legend()
plt.grid(axis='y', linestyle='--', alpha=0.5)
plt.tight_layout()
plt.savefig('violin_margen_deptos.png', dpi=300)
plt.show()

import matplotlib.pyplot as plt
from sklearn.metrics import RocCurveDisplay, ConfusionMatrixDisplay

# ------------------------------------------------------------
# 1. GENERAR modelo_predictivo_roc_confusion.png
# ------------------------------------------------------------
fig, axes = plt.subplots(1, 2, figsize=(14, 5))

# Curva ROC
RocCurveDisplay.from_estimator(model, X_test, y_test, ax=axes[0])
axes[0].plot([0, 1], [0, 1], 'k--', label='Clasificador Aleatorio (AUC=0.5)')
axes[0].set_title('Curva ROC - Predicción de Entregas Tardías', fontsize=14)
axes[0].legend()

# Matriz de Confusión
ConfusionMatrixDisplay.from_estimator(model, X_test, y_test,
                                      display_labels=['A Tiempo', 'Tardío'],
                                      normalize='true',
                                      ax=axes[1],
                                      cmap='Blues')
axes[1].set_title('Matriz de Confusión Normalizada', fontsize=14)

plt.tight_layout()
plt.savefig('modelo_predictivo_roc_confusion.png', dpi=300, bbox_inches='tight')
print("✅ modelo_predictivo_roc_confusion.png guardado")
plt.show()


# ------------------------------------------------------------
# 2. GENERAR importancia_coeficientes.png
# ------------------------------------------------------------
# Necesitamos los nombres de las features y los coeficientes
preprocessor.fit(X_train)
feature_names = (['order_item_quantity', 'sales'] +
                 list(preprocessor.named_transformers_['cat'].get_feature_names_out(
                     ['shipping_mode', 'category_name', 'customer_segment', 'order_region', 'order_state']
                 )))

coeficientes = model.named_steps['classifier'].coef_[0]

importancia_df = pd.DataFrame({
    'Feature': feature_names,
    'Coeficiente': coeficientes
}).sort_values('Coeficiente', ascending=False)

# Graficar los Top 10
plt.figure(figsize=(10, 6))
top_features = importancia_df.head(10)
sns.barplot(data=top_features, x='Coeficiente', y='Feature', palette='coolwarm')
plt.title('Top 10 Factores que más influyen en el Retraso (Logística)', fontsize=14)
plt.xlabel('Coeficiente (Impacto en el log-odds)')
plt.grid(axis='x', linestyle='--', alpha=0.7)
plt.tight_layout()
plt.savefig('importancia_coeficientes.png', dpi=300, bbox_inches='tight')
print("✅ importancia_coeficientes.png guardado")
plt.show()